Repository mjseok/OSS_team1, pull requests merged in 2020-05, with the labels that each got.

#6 FIX:Warning resolution
  LICENSE
Labels: bug

#7 COR:Change variable name
  Code.c
Labels: documentation

#11 FIX:Fix error
  Code.c
Labels: bug

#8 Function/change name
  Code.c
Labels: documentation

#16 Error/runtime error
  Code.c
Labels: bug

#21 Error/fix after test
  Code.c
Labels: bug

#23 ADD:Add error message
  Code.c
Labels: bug, enhancement

#24 COR:Correct global variable to local variable
  Code.c
Labels: clean code

#25 COR:Correct magic number
  Code.c
Labels: clean code

#28 FIX:Fix variable name
  Code.c
Labels: bug

#29 ADD:Add leaderboard function
  Code.c
Labels: enhancement

#32 COR:Change for readability
  Code.c
Labels: clean code
